/// A Canvas quiz expressed in QTI 1.2 / Canvas-CC format.
///
/// Each quiz becomes two resources in the cartridge:
/// - `g<id>/assessment_qti.xml` — the IMS QTI 1.2 question definitions
/// - `g<id>/assessment_meta.xml` — Canvas-specific quiz metadata
///   (description, due date, attempts, scoring policy, group)
///
/// Plus a copy at `non_cc_assessments/g<id>.xml.qti` (Canvas's exporter
/// duplicates the QTI there; the importer reads either copy).
class Quiz {
  /// Slug used to derive the quiz's IMS identifier (`imsId('quiz:<slug>')`).
  final String slug;

  final String title;

  /// Lecture week this quiz belongs to. Drives module placement.
  final int week;

  /// Total points across all questions. Currently sourced as
  /// `sum(questions.points)` so authors don't have to keep a separate
  /// total in sync with the question list.
  num get pointsPossible =>
      questions.fold<num>(0, (s, q) => s + q.points);

  final DateTime? dueAt;

  /// Long-form quiz description rendered as the quiz's intro page in
  /// Canvas (HTML allowed; will be CDATA-escaped on emission).
  final String descriptionHtml;

  /// Slug of the assignment group this quiz lives in (e.g. `lectures`).
  final String groupSlug;

  /// Number of attempts allowed. Default 1 for low-stakes comprehension
  /// quizzes; -1 means unlimited.
  final int allowedAttempts;

  /// Policy when multiple attempts are allowed: `keep_highest`, `keep_latest`,
  /// or `keep_average`.
  final String scoringPolicy;

  /// Slug of the auto-paired remediation assignment (created by the loader),
  /// for cross-reference in the quiz description and grader rationale.
  final String remediationAssignmentSlug;

  final List<QuizQuestion> questions;

  const Quiz({
    required this.slug,
    required this.title,
    required this.week,
    required this.descriptionHtml,
    required this.groupSlug,
    required this.questions,
    required this.remediationAssignmentSlug,
    this.dueAt,
    this.allowedAttempts = 1,
    this.scoringPolicy = 'keep_highest',
  });
}

class QuizQuestion {
  /// Stable slug used for the question's IMS identifier. Generated by the
  /// loader as `<quiz-slug>-q<index>` if not provided.
  final String slug;

  /// HTML question text (will be CDATA-escaped on emission).
  final String textHtml;

  /// Per-question point value. Total across the quiz is the sum of these.
  final num points;

  final List<QuizChoice> choices;

  const QuizQuestion({
    required this.slug,
    required this.textHtml,
    required this.choices,
    this.points = 1,
  });

  int get correctIndex {
    for (var i = 0; i < choices.length; i++) {
      if (choices[i].isCorrect) return i;
    }
    throw StateError(
        'quiz question "$slug" has no choice marked correct: true');
  }
}

class QuizChoice {
  /// Plain-text choice label (rendered as `texttype="text/plain"`).
  final String text;

  final bool isCorrect;

  /// Feedback shown when this specific choice is selected. Plain text;
  /// leave empty to suppress feedback for this choice. The C-3
  /// remediation workflow uses these to point to companion cheat sheets.
  final String feedback;

  /// Optional companion cheat sheet slug. When set, the rendered feedback
  /// includes a "See cheatsheet-X" pointer.
  final String? cheatsheetSlug;

  const QuizChoice({
    required this.text,
    required this.isCorrect,
    this.feedback = '',
    this.cheatsheetSlug,
  });
}
